Dictionary to DataFrame or Series

In [1]:
import pandas as pd

In [2]:
data = {
    'name':['rashed','sabit','prio'],
    'age':[23,24,23],
    'city':['jamalpur','serpur','rangpur']
}

In [3]:
data

{'name': ['rashed', 'sabit', 'prio'],
 'age': [23, 24, 23],
 'city': ['jamalpur', 'serpur', 'rangpur']}

In [4]:
name_series = pd.Series(data['name'],name='Name')
name_series

0    rashed
1     sabit
2      prio
Name: Name, dtype: object

In [5]:
df = pd.DataFrame(data)
df

     name  age      city
0  rashed   23  jamalpur
1   sabit   24    serpur
2    prio   23   rangpur

In [6]:
age_series = df['age']
age_series

0    23
1    24
2    23
Name: age, dtype: int64

In [7]:
city_series = df['city']
city_series

0    jamalpur
1      serpur
2     rangpur
Name: city, dtype: object