In [4]:
import pandas as pd

In [5]:
df =pd.read_csv("fuel.csv")

In [8]:
df.head(5)

,country,sub_region,iso3,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,South Asia,PAK,1.64,1.86,1.25,180,3.7,85,450,0.4,True,5.2,42.5,2026-04-04,27.3
1,India,South Asia,IND,1.11,1.03,1.08,280,8.4,85,5340,2.4,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,South Asia,BGD,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,South Asia,LKA,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,South Asia,NPL,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   country                    22 non-null     object
 1   sub_region                 22 non-null     object
 2   iso3                       22 non-null     object
 3   gasoline_usd_per_liter     22 non-null     float64
 4   diesel_usd_per_liter       22 non-null     float64
 5   lpg_usd_per_kg             22 non-null     float64
 6   avg_monthly_income_usd     22 non-null     int64
 7   fuel_affordability_index   22 non-null     float64
 8   oil_import_dependency_pct  22 non-null     int64
 9   refinery_capacity_kbpd     22 non-null     int64
 10  ev_adoption_pct            22 non-null     float64
 11  fuel_subsidy_active        22 non-null     bool
 12  subsidy_cost_bn_usd        22 non-null     float64
 13  co2_transport_mt           22 non-null     float64
 14  price_date                 22 non-null     object
 15  gasoline_pct_daily_wage    22 non-null     float64
dtypes: bool(1), float64(8), int64(3), object(4)
memory usage: 2.7+ KB

Delete Columns Using "del"

In [10]:
del df["iso3"]

In [12]:
df.head()

,country,sub_region,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,South Asia,1.64,1.86,1.25,180,3.7,85,450,0.4,True,5.2,42.5,2026-04-04,27.3
1,India,South Asia,1.11,1.03,1.08,280,8.4,85,5340,2.4,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,South Asia,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,South Asia,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,South Asia,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5

Delete Columns Using "pop"

In [13]:
df.pop("sub_region")

0         South Asia
1         South Asia
2         South Asia
3         South Asia
4         South Asia
5         South Asia
6          East Asia
7          East Asia
8          East Asia
9          East Asia
10         East Asia
11    Southeast Asia
12    Southeast Asia
13    Southeast Asia
14    Southeast Asia
15    Southeast Asia
16    Southeast Asia
17    Southeast Asia
18    Southeast Asia
19    Southeast Asia
20    Southeast Asia
21    Southeast Asia
Name: sub_region, dtype: object

In [14]:
df.head()

,country,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,1.64,1.86,1.25,180,3.7,85,450,0.4,True,5.2,42.5,2026-04-04,27.3
1,India,1.11,1.03,1.08,280,8.4,85,5340,2.4,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5

In [ ]:
Delete Columns Using "drop"

In [25]:
x =df.drop('ev_adoption_pct',axis=1).head()

In [26]:
x

,country,gasoline_usd_per_liter,diesel_usd_per_liter,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,1.64,1.86,180,3.7,85,450,True,5.2,42.5,2026-04-04,27.3
1,India,1.11,1.03,280,8.4,85,5340,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,1.07,0.93,160,5.0,100,33,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,1.34,1.19,210,5.2,100,50,False,0.0,8.5,2026-04-04,19.1
4,Nepal,1.34,1.21,120,3.0,100,0,False,0.0,4.3,2026-04-04,33.5

In [29]:
y = df[['ev_adoption_pct']]

In [30]:
y

    ev_adoption_pct
0               0.4
1               2.4
2               0.1
3               0.2
4               0.6
5               0.0
6              10.2
7               3.5
8              10.5
9               5.0
10              0.1
11              4.2
12              2.8
13              0.5
14              0.7
15              0.4
16              5.8
17              0.0
18              0.0
19              0.0
20              0.2
21              0.0